### ISSUE TITLE
佬，有bug

### ISSUE THREAD

**Issue by lo1kda** [feverrun/my_scripts#20]
❗️lzkj_v2 邀请入会有礼, 错误!
ReferenceError: proecy is not defined
    at /ql/data/scripts/feverrun_my_scripts/jd_lzkj_v2_yqrhyl.js:16:34551
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by feverrun** [comment]
> ❗️lzkj_v2 邀请入会有礼, 错误! ReferenceError: proecy is not defined at /ql/data/scripts/feverrun_my_scripts/jd_lzkj_v2_yqrhyl.js:16:34551 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

更新

**Comment by 1391959853** [comment]
佬，代理有bug，明明ip已经加入了白名单。还是提示407，代理平台是豆芽，套餐为不限量套餐

错误码1: synthesisCard - ERR_BAD_REQUEST
407
错误码1: synthesisCard - ERR_BAD_REQUEST
407
错误码1: synthesisCard - ERR_BAD_REQUEST
407
错误码1: tsService - ERR_BAD_REQUEST
407

**Comment by feverrun** [comment]
> 佬，代理有bug，明明ip已经加入了白名单。还是提示407，代理平台是豆芽，套餐为不限量套餐
> 
> 错误码1: synthesisCard - ERR_BAD_REQUEST 407 错误码1: synthesisCard - ERR_BAD_REQUEST 407 错误码1: synthesisCard - ERR_BAD_REQUEST 407 错误码1: tsService - ERR_BAD_REQUEST 407

是不是需要用户名和密码才能访问？
